### ISSUE TITLE
Impossible to get alignment from marian-dev 

### ISSUE THREAD

**Issue by 520jefferson** [amunmt/marian#231]
I can get alignment from marian but  marian-dev doesn't supply return-alignment, What is the consideration?

**Comment by 520jefferson** [comment]
Could you tell me the logic of getting the alignment when decoding with transformer ?

**Comment by emjotde** [comment]
We do not have this feature yet. 

Also, it is by principle not clear how to actually implement that for the transformer. It has 48 target-to-source attention matrices (6 layers x 8 heads). Which one would be the correct one to choose?
