### ISSUE TITLE
Create yaml vocabulary for each input file if none given

### ISSUE THREAD

**Issue by emjotde** [amunmt/marian#26]
I think this should be an extension of the `Vocab` class.

Create yaml vocabulary for each input file `filename` if none given:
1) search for `filename.{yml,json}`, if exists load as vocab. 

Else:

2) create a frequency list for that particular file, 
3) sort by frequency
4) assign id from rank
5) create yml representation
6) dump representation to `filename.yml`

**Comment by hieuhoang** [comment]
done. Add
  --create-vocabs
WIll create the files specified by -v args if they don't exist
