### ISSUE TITLE
Potential race condition?

### ISSUE THREAD

**Issue by afaji** [amunmt/marian#37]
https://github.com/amunmt/marian/blob/master/src/training/graph_group.h  line 73

Should we put cudaStreamSynchronize(0) here? I believe Cuda operations do not block CPU, thus you will finish the pushGradient function  (and free the lock) even though the param update is not complete yet.

**Comment by afaji** [comment]
addition:
after some tests with 2 GPUs, I got:

with stream sync : Ep. 151 Up. 4500 : Sen. 256 : Cost 74.35 
without sync        : Ep. 151 : Up. 4500 : Sen. 256 : Cost 106.45

**Comment by emjotde** [comment]
This is some toymodel? I was training with normal models and did not see any difference from single gpu model. And wouldn't that synchronize automatically as copyFrom is called from stream 0 and the following updates as well?

**Comment by emjotde** [comment]
There is a cudaStreamSynchronize(0) in copyFrom. So that can't be it.

**Comment by afaji** [comment]
because you use single GPU, (there is if-statement to handle single GPU). Try with more than one

yes, there is synchronize in copyFrom, but not in parameter update.

**Comment by emjotde** [comment]
I was testing with 3 GPUs, but misunderstood which update you mean. OK, let's check again.

**Comment by afaji** [comment]
Try this

`    void pushGradients(Tensor newGrads) {
      if(graphs_.size() < 2) {
        opt_->update(graphs_[0]);
      }
      else {
        std::lock_guard<std::mutex> guard(sync_);
        // add instead of copy?
        grads_->copyFrom(newGrads);
        opt_->update(params_, grads_);
      }
    }
`

versus this

`    void pushGradients(Tensor newGrads) {
      if(graphs_.size() < 2) {
        opt_->update(graphs_[0]);
      }
      else {
        std::lock_guard<std::mutex> guard(sync_);
        // add instead of copy?
        grads_->copyFrom(newGrads);
        opt_->update(params_, grads_);
        cudaStreamSynchronize(0);
      }
    }
`

Also make sure use more than 1 GPU because the if-statement above.

**Comment by emjotde** [comment]
OK, I think you are right. It also seem that the speed of your implementation matches now my implementation without sharding. To fix this issue I will probably just pull your pull request.

**Comment by afaji** [comment]
have you check the non-sharding speed with synchronize? I believe that might slow it down a bit.

I still need to verify the correctness of my PR in terms of convergence.

**Comment by emjotde** [comment]
I will post stats in a moment under the pull request
