### ISSUE TITLE
NVIDIA Sample EULA requires a statement

### ISSUE THREAD

**Issue by AngusL** [amunmt/marian#47]
```src/3rd_party/reduce_all.h``` appears to derive from an NVIDIA CUDA SDK sample. This looks to be fine, but [the EULA](http://docs.nvidia.com/cuda/eula/index.html#source-code) requires a statement: "This software contains source code provided by NVIDIA Corporation."

**Comment by emjotde** [comment]
No problem, where would we put that, in the readme, in the license?

**Comment by AngusL** [comment]
I'd suggest the 'acknowledgements' part of the README, but the LICENSE would be sensible, too.

Thanks!
