### ISSUE TITLE
Seed all random number generators

### ISSUE THREAD

**Issue by kpu** [amunmt/marian#52]
@AngusL points out that Marian is non-deterministic which makes regression tests hard (paging @afaji).  Moreover https://github.com/amunmt/marian/blob/13ee36be159386f93259c3c6c8bfd80db5f52fff/src/training/config.cpp#L154 is misleading because it says "for all random number generators".  

https://github.com/amunmt/marian/blob/9ce67850b80b0be5fb3d2a51c645b45ac170786d/src/data/batch_generator.h#L111 should change from the deprecated two-argument `random_shuffle' to the three-argument seeded version.  

https://github.com/amunmt/marian/blob/13ee36be159386f93259c3c6c8bfd80db5f52fff/src/data/corpus.cpp#L44 does seed.

**Comment by emjotde** [comment]
Yes, that's a bug. Should use the seed everywhere.

**Comment by snukky** [comment]
#53
